### PR TITLE
Replace 'master account' with 'primary account'

### PR DESCRIPTION
**Pull request by jonambas**
### What's Changed
- Replaces the use of "master account" with "primary account"

---

### Support Docs Update Checklist

Note: when you open a pull request, your changes are published to https://staging.sparkpost.com/docs.

Please take a moment to check each of these steps for your pull request:

- [x] Give your pull request a meaningful name.
- [x] Include a description of your changes in the pull request.
- [ ] _SparkPost staff only_: Check that your article appears [here](https://staging.sparkpost.com/docs) and looks correct.
- [ ] Check the links in your article.
- [ ] Use lowercase filenames.

### CODE REVIEW

**Review by ndurant-sp — APPROVED** [review]

**Comment by ndurant-sp** [comment]
Have we already communicated this with CST, so that they are also using consistent wording?

**Comment by jonambas** [comment]
@ndurant-sp Not yet, this is something that will be communicated along with the hibana launch soon

**Comment by rdawemsys** [comment]
We should also update our internal admin endpoint documentation to use the same terminology. Who is working on / going to work on that?

**Comment by jonambas** [comment]
@rdawemsys Not sure! I've been working on anything external-facing (I have app and api doc PRs ready), but I don't think  anyone's looking at internal docs yet.

**Pull request merged**
